language: python

python:
  - 3.6

before_install:
  - export PYTHONPATH=$HOME/builds/jay-johnson/spylunking
  - export PIP_USE_MIRRORS=true

install:
  - pip install -e .

script:
  - echo "Running Lint Tests"
  - flake8
  - pycodestyle
  - echo "Running Tox"
  - tox
